import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth/next";
import { createClient } from "@supabase/supabase-js";
import { pushTaskToCalendar } from "@/lib/gcal";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";

export async function POST(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions);
    if (!session || !session.user?.email) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const primaryEmail = session.user.email.toLowerCase();
    const body = await req.json();
    const { blocks } = body;

    if (!blocks || !Array.isArray(blocks)) {
      return NextResponse.json({ error: "Invalid payload" }, { status: 400 });
    }

    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
    const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "";
    const supabase = createClient(supabaseUrl, supabaseAnonKey);

    // Get primary account token from vault
    const { data: account, error } = await supabase
      .from("connected_accounts")
      .select("*")
      .eq("user_email", primaryEmail)
      .eq("account_email", primaryEmail)
      .single();

    if (error || !account) {
      throw new Error("Failed to fetch primary account token");
    }

    let accessToken = account.access_token;

    // Refresh if needed
    if (account.expires_at < Date.now() + 60000) {
      const tokenUrl = "https://oauth2.googleapis.com/token";
      const res = await fetch(tokenUrl, {
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: new URLSearchParams({
          client_id: process.env.GOOGLE_CLIENT_ID || "",
          client_secret: process.env.GOOGLE_CLIENT_SECRET || "",
          grant_type: "refresh_token",
          refresh_token: account.refresh_token,
        }),
      });
      const refreshedTokens = await res.json();
      if (res.ok && refreshedTokens.access_token) {
        accessToken = refreshedTokens.access_token;
        const newExpiresAt = Date.now() + refreshedTokens.expires_in * 1000;
        await supabase.from("connected_accounts").update({
          access_token: accessToken,
          expires_at: newExpiresAt,
        }).eq("id", account.id);
      }
    }

    // Now push all blocks to calendar
    let pushedCount = 0;

    for (const block of blocks) {
      // Create a mock "task" object to re-use the pushTaskToCalendar function
      // pushTaskToCalendar expects a deadline. We will map block.endTime to deadline
      // and map block.startTime to... wait! pushTaskToCalendar creates an event 1 hour before deadline.
      // We need to write a custom push logic here instead of using pushTaskToCalendar
      // because Smart Schedule blocks have exact start and end times!
      
      const event = {
        summary: `[Campus OS] ${block.title}`,
        description: `Generated by Smart Schedule\nType: ${block.type}`,
        start: { dateTime: new Date(block.startTime).toISOString() },
        end: { dateTime: new Date(block.endTime).toISOString() },
        reminders: {
          useDefault: false,
          overrides: [{ method: "popup", minutes: 30 }],
        },
      };

      const response = await fetch("https://www.googleapis.com/calendar/v3/calendars/primary/events", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify(event),
      });

      if (response.ok) {
        pushedCount++;
      }
    }

    return NextResponse.json({ success: true, pushedCount });
  } catch (error: any) {
    console.error("[Push API] Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
